import type { Vehicle } from './VehicleList'

// Services reuse the Vehicle shape so service pages render through VehicleDetail
// with an identical layout. `seats` holds the card tagline; `luggage` is unused.

const PH = 'https://res.cloudinary.com/dckyndryf/image/upload/f_auto,q_auto,w_900,c_limit/IMG_0938_fhylhh'

/** Real airport photos — first is the card, the rest fill the service gallery. */
export const AIRPORT_TRANSFER_IMAGES = [
  'https://res.cloudinary.com/dp4cbs8c2/image/upload/f_auto,q_auto,w_1200,c_limit/v1783787064/IMG_6170_fxbudt.jpg',
  'https://res.cloudinary.com/dp4cbs8c2/image/upload/f_auto,q_auto,w_1200,c_limit/v1783784630/20260211_134438550_iOS_okfp39.jpg',
]

export const SERVICES: Vehicle[] = [
  {
    slug:        'airport-transfers',
    name:        'Airport Transfers',
    badge:       'Transfers',
    image:       AIRPORT_TRANSFER_IMAGES[0],
    images:      AIRPORT_TRANSFER_IMAGES,
    seats:       'All major UK airports',
    luggage:     'Luggage assistance included',
    description: 'Reliable airport transfers to and from all major UK airports: on-time pickups, luggage assistance and stress-free journeys for individuals and groups.',
    features:    ['Live flight tracking', 'Meet & greet service', '24/7 availability', 'Luggage assistance', 'Professional uniformed drivers', 'Child seats on request'],
    idealFor:    ['Business Travellers', 'Family Holidays', 'Group Travel', 'Wedding Parties', 'Sports Teams', 'Tour Groups'],
  },
  {
    slug:        'corporate',
    name:        'Corporate Travel',
    badge:       'Corporate',
    image:       PH,
    seats:       'Executive business transport',
    luggage:     'Luggage assistance included',
    description: 'Executive transport for business: punctual, professional and properly presented, from single-passenger chauffeur cars to full-team coaches.',
    features:    ['Punctual, professional service', 'Uniformed chauffeurs', 'Onboard WiFi', 'Privacy glass', 'Account management available', 'Flexible scheduling'],
    idealFor:    ['Corporate Events', 'Business Roadshows', 'Airport Transfers'],
  },
  {
    slug:        'private-hire',
    name:        'Private Hire',
    badge:       'Private Hire',
    image:       PH,
    seats:       'Your schedule, your route',
    luggage:     'Luggage assistance included',
    description: 'Premium vehicles on your schedule. Flexible private hire for day trips, nights out and bespoke journeys anywhere in the UK.',
    features:    ['Fully flexible itineraries', 'Door-to-door service', 'Premium vehicles', 'Professional uniformed drivers', 'Extended waiting available', 'Refreshments on request'],
    idealFor:    ['Day Trips', 'Special Occasions', 'Family Travel'],
  },
  {
    slug:        'weddings-events',
    name:        'Wedding & Events',
    badge:       'Weddings',
    image:       PH,
    seats:       'Bridal & guest logistics',
    luggage:     'Luggage assistance included',
    description: 'Seamless bridal and guest transport so your day runs exactly as planned, with immaculate vehicles dressed to match the occasion.',
    features:    ['Ribbons & decoration on request', 'Bridal car & guest shuttles', 'Red carpet on arrival', 'Champagne on request', 'Dedicated event coordinator', 'Immaculate presentation'],
    idealFor:    ['Weddings', 'Proms', 'Special Occasions'],
  },
  {
    slug:        'school-trips',
    name:        'School Transport',
    badge:       'Education',
    image:       PH,
    seats:       'Safe, reliable school travel',
    luggage:     'Luggage assistance included',
    description: 'Safe, reliable transport for schools and colleges, with DBS-checked drivers and well-maintained vehicles for trips, tours and daily runs.',
    features:    ['DBS-checked drivers', 'Seatbelts on every seat', 'Risk-assessment support', 'Wheelchair-accessible options', 'Experienced school-run drivers', 'Air conditioning'],
    idealFor:    ['School Trips', 'Educational Tours', 'Sports Fixtures'],
  },
  {
    slug:        'group-travel',
    name:        'Group Travel and Tours',
    badge:       'Tours',
    image:       PH,
    seats:       'UK & Europe group tours',
    luggage:     'Large luggage hold',
    description: 'Day trips and extended tours across the UK and into Europe, with comfortable coaches and full itinerary support for groups of any size.',
    features:    ['UK & Europe coverage', 'Itinerary planning support', 'Onboard WiFi', 'Reclining seats', 'Large luggage hold', 'Onboard WC on coaches'],
    idealFor:    ['Group Tours', 'Days Out', 'Europe Trips'],
  },
  {
    slug:        'sports-team-travel',
    name:        'Sports Team Travel',
    badge:       'Sports',
    image:       PH,
    seats:       'Match-day travel for teams',
    luggage:     'Kit & equipment storage',
    description: 'Match-day travel for clubs and teams: kit storage, flexible scheduling and experienced drivers who know the fixture-day routine.',
    features:    ['Kit & equipment storage', 'Flexible match-day scheduling', 'Onboard WiFi', 'USB charging at every seat', 'Air conditioning', 'Experienced team drivers'],
    idealFor:    ['Sports Teams', 'Away Fixtures', 'Tournaments'],
  },
  {
    slug:        'cruise-port-transfers',
    name:        'Cruise Port Transfers',
    badge:       'Transfers',
    image:       PH,
    seats:       'Door to dock, luggage and all',
    luggage:     'Luggage assistance included',
    description: 'Door-to-dock transfers to all major UK cruise ports: punctual arrivals and a hand with every case, for families and full groups.',
    features:    ['All major UK cruise ports', 'Luggage assistance', 'Punctual arrivals', 'Group & family friendly', 'Meet & greet available', '24/7 availability'],
    idealFor:    ['Cruise Departures', 'Family Holidays', 'Group Travel'],
  },
  {
    slug:        'executive-travel',
    name:        'Executive Travel',
    badge:       'VIP',
    image:       PH,
    seats:       'First-class travel for VIPs',
    luggage:     'Luggage assistance included',
    description: 'First-class travel for VIPs and discerning clients: discreet chauffeurs, flagship vehicles and concierge-level attention to detail.',
    features:    ['Luxury chauffeur-driven vehicles', 'Privacy glass', 'Bottled water provided', 'Concierge-level service', 'Discreet professional drivers', 'Flexible scheduling'],
    idealFor:    ['VIP Clients', 'Corporate Travel', 'Airport Transfers'],
  },
]
